### ISSUE TITLE
feat: enable storage account geo replication (SNYK-CC-AZURE-649)

### ISSUE THREAD

**Issue by helenakallekleiv** [equinor/terraform-azurerm-sql#62]
**Message:** Storage Account geo-replication disabled ([SNYK-CC-AZURE-649](https://snyk.io/security-rules/SNYK-CC-AZURE-649))
**Severity:** `Medium`

Detailed paths

    Introduced through: resource › azurerm_storage_account[this] › account_replication_type

This issue is...
- Storage Account geo-replication disabled

The impact of this is...
- Data might be exposed to the risk of loss or unavailability

You can resolve it by...
- Set sku.name to either GRS, RAGRS, GZRS or RAGZRS

#### References
- [Azure Storage redundancy](https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy)
- [azurerm_storage_account](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account)
- [Microsoft.Storage storageAccounts](https://learn.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?tabs=json&pivots=deployment-language-terraform)

**Comment by hknutsen** [comment]
Check if Microsoft has any recommendations for storage accounts used for SQL audit logs and vuln assessments.

**Comment by helenakallekleiv** [comment]
There is no specific reccomendations that I could find from Microsoft, regarding geo-replication on SQL server-level auditing or vulverability assessment. Although there is an Azure Policy stating that SQL Database should avoid using GRS backup redundancy (ref. https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/SQL/SqlDb_BlockGrsBackupRedundancy_Deny.json)

`GRS` SKU is compatible with legacy blob `BlobStorage`, which is set for the storage acc. type now, but the reccomended storage acc. type is `StandardV2` for all SKU's. Ref. https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy#supported-storage-account-types

Any thoughts on this?

**Comment by helenakallekleiv** [comment]
Resolved, closing this.
