### ISSUE TITLE
feat: set email attributes for SQL threat alerts (SNYK-CC-TF-169/170)

### ISSUE THREAD

**Issue by helenakallekleiv** [equinor/terraform-azurerm-sql#66]
Stems from two related SNYK issues for the `azurerm_mssql_server_security_alert_policy`-resource:

- Missing email recipients for SQL threat alerts ([SNYK-CC-TF-169](https://snyk.io/security-rules/SNYK-CC-TF-169))
  - **Severity:** `Low`
  - **Issue:** Azure SQL Threat detection policy is missing email recipients
  - **Impact:** Alerts may not be delivered to the analysts
  - **Resolve:** Set `email_addresses` attribute

- SQL Advanced Threat alerts are not send to admins ([SNYK-CC-TF-170](https://snyk.io/security-rules/SNYK-CC-TF-170))
  - **Severity:** `Low`
  - **Issue:** SQL Advanced Threat alerts are not send to admins
  - **Impact:** Account administrators might not be informed about SQL advanced threats
  - **Resolve:** Set `email_account_admin` attribute to `true`

**Comment by hknutsen** [comment]
Email subscription admins could be enabled by default.

Custom email addresses should be an optional feature to not make this a breaking change.
