### ISSUE TITLE
chore: should mssql vuln assessment email notifications be enabled (SNYK-CC-AZURE-540)

### ISSUE THREAD

**Issue by helenakallekleiv** [equinor/terraform-azurerm-sql#67]
SNYK-issue for the `azurerm_mssql_server_vulnerability_assessment`-resource: 
- MSSQL Vulnerability Assessment email notifications are disabled ([SNYK-CC-AZURE-540](https://snyk.io/security-rules/SNYK-CC-AZURE-540))
  - **Severity:** `Low`
  - **Issue:** MSSQL Vulnerability Assessment email notifications are disabled
  - **Impact:** Administrators will not be automatically notified, which can lead to time delay in identifying risks and taking corrective measures
  - **Resolve:** Set `recurring_scans.email_subscription_admins` to `true`

**Comment by hknutsen** [comment]
Investigate what information is in a vuln assessment, and decide if its contents are relevant for a subscription owner. If yes, then this should be enabled by default.

**Comment by helenakallekleiv** [comment]
The email notifications include a report from scans executed during the preceding week. The report displays approx. the same as the information shown in the Azure portal i would assume, although i couldn't seem to find docs with explicit examples on this. The report content displayed in the portal includes an overview of security state of the database, number of issues found, severity summary and a list of further investigations, as well as the va rule-number.

Ref.:
- https://learn.microsoft.com/en-us/azure/defender-for-cloud/sql-azure-vulnerability-assessment-overview
- https://learn.microsoft.com/en-us/azure/defender-for-cloud/sql-azure-vulnerability-assessment-enable?tabs=classic
- https://eccouncil.org/cybersecurity-exchange/ethical-hacking/how-to-write-vulnerability-assessment-report/
- https://learn.microsoft.com/en-us/azure/defender-for-cloud/sql-azure-vulnerability-assessment-find?tabs=classic#remediate-vulnerabilities-1

**Comment by helenakallekleiv** [comment]
I've ignored the associated issues in SNYK as this is closed, linking to #88.
